name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Sound Package
      run: sudo apt-get install libasound2-dev
    - name: npm install, build
      run: |
        cd server
        npm install -g node-gyp
        npm ci
        npm run build
      env:
        CI: true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: "server_build"
        # Directory containing files to upload
        path: "server/build/"
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: xz
        GHR_PATH: server/build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
